name: Run Unit Tests
on: push
jobs:
  build:
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test:unit
    - name: Upload Coverage to Codacy
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
